version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_test
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '8080:8080'  # Update to your app's listening port
    environment:
      DATABASE_URL: 'postgresql://postgres:123@db:5432/auth_test?schema=public'
      JWT_SECRET: secret
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  # test:
  #   build:
  #     context: .
  #     target: test  # Specify the test stage in the Dockerfile
  #   command: npm run test  # Command to run Jest tests
  #   environment:
  #     # Include necessary environment variables for the tests
  #     DATABASE_URL: 'postgresql://postgres:123@db:5432/auth_test?schema=public'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app  # Mount your app's code into the container
